Update compilation.yml

diff --git a/.github/workflows/compilation.yml b/.github/workflows/compilation.yml
--- a/.github/workflows/compilation.yml
+++ b/.github/workflows/compilation.yml
@@ -57,23 +57,27 @@ jobs:
       - name: Show Rust CPU info
         run: rustc --print cfg
 
-      - name: Compile ${{ matrix.config.binaries }} build
-        run: |
-          cargo clean
-          cargo build --release --target $BINARY
+    - name: Compile ${{ matrix.config.binaries }} build
+      run: |
+        cargo clean
+        cargo build --release --target $BINARY
 
-          # Use conditional stripping based on the operating system
-          if [ "${{ runner.os }}" != "Windows" ]; then
-            strip target/$BINARY/release/${{ matrix.config.simple_name }}$EXT
-          else
-            strip target/$BINARY/release/${{ matrix.config.simple_name }}.exe
-          fi
+        BINARY_PATH="target/$BINARY/release/monty$EXT"
 
-          # Run the signature script with WINE_PATH, if applicable
-          WINE_PATH="$SDE" ../tests/signature.sh $benchref
+        # Ensure the binary exists before attempting to strip it
+        if [ -f "$BINARY_PATH" ]; then
+          strip "$BINARY_PATH"
+        else
+          echo "Error: Binary not found at $BINARY_PATH"
+          exit 1
+        fi
 
-          # Move the stripped binary to the destination directory
-          mv ./target/$BINARY/release/${{ matrix.config.simple_name }}$EXT ../${{ matrix.config.simple_name }}-$BINARY$EXT
+        # Run the signature script with WINE_PATH, if applicable
+        WINE_PATH="$SDE" ../tests/signature.sh $benchref
+
+        # Move the stripped binary to the destination directory
+        mv "$BINARY_PATH" "../${{ matrix.config.simple_name }}-$BINARY$EXT"
+
 
       - name: Remove non src files
         run: git clean -fx
